# If my open source projects were useful somehow, please, consider support my work. 
# Any contribution will be most welcome and a great incentive to keep efforts on creating useful projects.

github: tjas
